export const GET_ALL_COURSES = "GET_ALL_COURSES"
export const GET_COURSE_BY_ID = "GET_COURSE_BY_ID"
export const GET_ALL_COURSES_OPTIONS = "GET_ALL_COURSES_OPTIONS"
export const FETCH_WORKSHOP = "FETCH_WORKSHOP"
