export const DO_LOGIN = "DO_LOGIN"
export const UPDATE_ROLE = "UPDATE_ROLE"
export const LOGOUT = "LOGOUT"
export const UPDATE_KYC = "UPDATE_KYC"
export const VERIFY_OTP_TAB = "VERIFY_OTP_TAB"
export const CREATE_PASSWORD_TAB = "CREATE_PASSWORD_TAB"
